[package]
name = "vmrp-windows"
version = "0.1.0"
edition = "2021"

[dependencies]
vmrp-abi = { path = "../../crates/vmrp-abi" }
vmrp-core = { path = "../../crates/vmrp-core" }
vmrp-cpu = { path = "../../crates/vmrp-cpu" }
vmrp-platform = { path = "../../crates/vmrp-platform" }
vmrp-runtime = { path = "../../crates/vmrp-runtime" }
